PRESERVE DATA
alex1779/personal-portfolio-site pull request #14
Opened 2022-10-21 00:35 UTC by alex1779

DESCRIPTION ON COMING....

2022-10-22 21:53 UTC, sajid-munawar requested changes
# Changes Required 
 ### Hi @alex1779 
 Nice job, you are almost there.
 
 ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
 
 ## (Highlights) Good Points: 
 * Good commit messages. :heavy_check_mark:
 * No linter errors. :heavy_check_mark:
 * Followed Github flow :heavy_check_mark:
 * Professional README file. :heavy_check_mark:
 * PR has a good title and summary :heavy_check_mark:

 ## (Changes Required) Aspects to improve: 
 * [ ]  Please check my inline comments.
 
 ## [Optional] suggestions:
 * Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
 **Cheers and Happy coding! :clap::clap::clap:**
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear
 Please, remember to tag @sajid-munawar in your question so I can receive the notification.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-22 21:53 UTC, sajid-munawar commented on js/index.js
> +  const dataStorage = { name: inputName, email: inputEmail, message: inputMessage };
- [ ] Nice implementation of object for you inputs, Kindly make sure we can send the input value and receive the value from the local storage. you can write your object as follow.👇

```
const dataStorage = {
    name: InputName.value,
    email: InputEmail.value,
    message: inputMessage.value,
};
```

2022-10-22 22:40 UTC, BenMukebo requested changes
Hi @alex1779, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️


 ## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 22:40 UTC, BenMukebo commented on js/index.js
> +  inputName.addEventListener('input', changeInput);
- [ ] According to the project requirements:  When the user changes the content of any input field in the form the data object is updated and saved to the local storage. In order to be saved to the local storage the data object is turned into a string using `JSON.stringify` or similar methods. Ie:

```
localStorage.setItem('contactFormInput', JSON.stringify(formData));
```

- In order to be used after retrieved from the local storage the saved string is turned back into an object using `JSON.parse` or similar methods.

```
let savedFormData = localStorage.getItem('contactFormInput');
savedFormData = JSON.parse(savedFormData);
```

- [ ] Make sure When the user loads the page, the code checks if there are any saved data in the local storage and if so the input fields are pre-filled with the data.

```
window.onload = () => {
  let savedFormData = localStorage.getItem('contactFormInput');
  savedFormData = JSON.parse(savedFormData);
  // Check if the form data object is found on localStorage
  if (savedFormData) {
  // populate inputs values if data was found
  // ex: nameInput.value = savedFormData.name
  }
};
```

- Please address this 👍🏻

2022-10-23 01:43 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @alex1779, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

-   No linter errors. :heavy_check_mark: 
-   Good README file. :heavy_check_mark: 
-   Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/9ab1354ab399a31c604186cd2e7c09a0d4704215a1eda3e29a02fc52bf3f6bf5/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6d474b31673838485a526132466c4b47627a2f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-23 01:53 UTC, merged